
---
version: "3.7"

services:

  botami:
    image: techblog/botami4:latest
    container_name: botami
    restart: always
    environment:
      - BOT_TOKEN=
      - ALLOWD_IDS=
    volumes:
      - ./botami/tokens:/opt/botami/tokens
