
---
version: "3.7"

services:

  botami:
    image: techblog/botami4:latest
    container_name: botami
    restart: always
    environment:
      - BOT_TOKEN=5628434379:AAENbvCrfSqr0Hn27_9fP5uIH8_G7n4bNz4
      - ALLOWD_IDS=367468362
    volumes:
      - ./botami/tokens:/opt/botami/token


